package com.blacaz.hubspot.models.dando;

public class DirectorsAndOfficersQuestionsRequest {

	private String current_d_o_liability_insurance_policy_holders;
	private String are_you_aware_of_any_ongoing_or_arising_claim_regarding_your_d_o_liability;
	private String the_company_and_its_subsidiaries_are_not_domiciled_or_incorporated_in_the_usa;
	private String the_company_and_its_subsidiaries_are_not_involved_in_the_following_sectors_airlines_biotechnology_m;
	private String the_company_and_its_subsidiaries_do_not_have_any_securities_including_equities_debt_shares_notes_bo;
	private String the_company_and_its_subsidiaries_have_been_in_continuous_operations_for_the_past_2_years_;
	private String the_company_and_its_subsidiaries_have_no_business_operations_assets_or_revenues_derived_from_busine;
	private String the_company_and_its_subsidiaries_have_total_assets_that_exceed_total_liabilities_and_that_there_is_;
	private String the_company_its_subsidiaries_and_its_directors_or_officers_after_full_enquiries_have_never_been_the;
	private String initial_starting_date;
	private String expiring_date;
	private String the_current_number_of_employees_does_not_exceed_120_employees;
	private String there_have_been_no_retrenchments_in_the_past_1_year_and_none_are_expected_over_the_next_1_year;
	
	
	public String getThe_current_number_of_employees_does_not_exceed_120_employees() {
		return the_current_number_of_employees_does_not_exceed_120_employees;
	}
	public void setThe_current_number_of_employees_does_not_exceed_120_employees(
			String the_current_number_of_employees_does_not_exceed_120_employees) {
		this.the_current_number_of_employees_does_not_exceed_120_employees = the_current_number_of_employees_does_not_exceed_120_employees;
	}
	public String getThere_have_been_no_retrenchments_in_the_past_1_year_and_none_are_expected_over_the_next_1_year() {
		return there_have_been_no_retrenchments_in_the_past_1_year_and_none_are_expected_over_the_next_1_year;
	}
	public void setThere_have_been_no_retrenchments_in_the_past_1_year_and_none_are_expected_over_the_next_1_year(
			String there_have_been_no_retrenchments_in_the_past_1_year_and_none_are_expected_over_the_next_1_year) {
		this.there_have_been_no_retrenchments_in_the_past_1_year_and_none_are_expected_over_the_next_1_year = there_have_been_no_retrenchments_in_the_past_1_year_and_none_are_expected_over_the_next_1_year;
	}
	public String getCurrent_d_o_liability_insurance_policy_holders() {
		return current_d_o_liability_insurance_policy_holders;
	}
	public void setCurrent_d_o_liability_insurance_policy_holders(String current_d_o_liability_insurance_policy_holders) {
		this.current_d_o_liability_insurance_policy_holders = current_d_o_liability_insurance_policy_holders;
	}
	public String getAre_you_aware_of_any_ongoing_or_arising_claim_regarding_your_d_o_liability() {
		return are_you_aware_of_any_ongoing_or_arising_claim_regarding_your_d_o_liability;
	}
	public void setAre_you_aware_of_any_ongoing_or_arising_claim_regarding_your_d_o_liability(
			String are_you_aware_of_any_ongoing_or_arising_claim_regarding_your_d_o_liability) {
		this.are_you_aware_of_any_ongoing_or_arising_claim_regarding_your_d_o_liability = are_you_aware_of_any_ongoing_or_arising_claim_regarding_your_d_o_liability;
	}
	public String getThe_company_and_its_subsidiaries_are_not_domiciled_or_incorporated_in_the_usa() {
		return the_company_and_its_subsidiaries_are_not_domiciled_or_incorporated_in_the_usa;
	}
	public void setThe_company_and_its_subsidiaries_are_not_domiciled_or_incorporated_in_the_usa(
			String the_company_and_its_subsidiaries_are_not_domiciled_or_incorporated_in_the_usa) {
		this.the_company_and_its_subsidiaries_are_not_domiciled_or_incorporated_in_the_usa = the_company_and_its_subsidiaries_are_not_domiciled_or_incorporated_in_the_usa;
	}
	public String getThe_company_and_its_subsidiaries_are_not_involved_in_the_following_sectors_airlines_biotechnology_m() {
		return the_company_and_its_subsidiaries_are_not_involved_in_the_following_sectors_airlines_biotechnology_m;
	}
	public void setThe_company_and_its_subsidiaries_are_not_involved_in_the_following_sectors_airlines_biotechnology_m(
			String the_company_and_its_subsidiaries_are_not_involved_in_the_following_sectors_airlines_biotechnology_m) {
		this.the_company_and_its_subsidiaries_are_not_involved_in_the_following_sectors_airlines_biotechnology_m = the_company_and_its_subsidiaries_are_not_involved_in_the_following_sectors_airlines_biotechnology_m;
	}
	public String getThe_company_and_its_subsidiaries_do_not_have_any_securities_including_equities_debt_shares_notes_bo() {
		return the_company_and_its_subsidiaries_do_not_have_any_securities_including_equities_debt_shares_notes_bo;
	}
	public void setThe_company_and_its_subsidiaries_do_not_have_any_securities_including_equities_debt_shares_notes_bo(
			String the_company_and_its_subsidiaries_do_not_have_any_securities_including_equities_debt_shares_notes_bo) {
		this.the_company_and_its_subsidiaries_do_not_have_any_securities_including_equities_debt_shares_notes_bo = the_company_and_its_subsidiaries_do_not_have_any_securities_including_equities_debt_shares_notes_bo;
	}
	public String getThe_company_and_its_subsidiaries_have_been_in_continuous_operations_for_the_past_2_years_() {
		return the_company_and_its_subsidiaries_have_been_in_continuous_operations_for_the_past_2_years_;
	}
	public void setThe_company_and_its_subsidiaries_have_been_in_continuous_operations_for_the_past_2_years_(
			String the_company_and_its_subsidiaries_have_been_in_continuous_operations_for_the_past_2_years_) {
		this.the_company_and_its_subsidiaries_have_been_in_continuous_operations_for_the_past_2_years_ = the_company_and_its_subsidiaries_have_been_in_continuous_operations_for_the_past_2_years_;
	}
	public String getThe_company_and_its_subsidiaries_have_no_business_operations_assets_or_revenues_derived_from_busine() {
		return the_company_and_its_subsidiaries_have_no_business_operations_assets_or_revenues_derived_from_busine;
	}
	public void setThe_company_and_its_subsidiaries_have_no_business_operations_assets_or_revenues_derived_from_busine(
			String the_company_and_its_subsidiaries_have_no_business_operations_assets_or_revenues_derived_from_busine) {
		this.the_company_and_its_subsidiaries_have_no_business_operations_assets_or_revenues_derived_from_busine = the_company_and_its_subsidiaries_have_no_business_operations_assets_or_revenues_derived_from_busine;
	}
	public String getThe_company_and_its_subsidiaries_have_total_assets_that_exceed_total_liabilities_and_that_there_is_() {
		return the_company_and_its_subsidiaries_have_total_assets_that_exceed_total_liabilities_and_that_there_is_;
	}
	public void setThe_company_and_its_subsidiaries_have_total_assets_that_exceed_total_liabilities_and_that_there_is_(
			String the_company_and_its_subsidiaries_have_total_assets_that_exceed_total_liabilities_and_that_there_is_) {
		this.the_company_and_its_subsidiaries_have_total_assets_that_exceed_total_liabilities_and_that_there_is_ = the_company_and_its_subsidiaries_have_total_assets_that_exceed_total_liabilities_and_that_there_is_;
	}
	public String getThe_company_its_subsidiaries_and_its_directors_or_officers_after_full_enquiries_have_never_been_the() {
		return the_company_its_subsidiaries_and_its_directors_or_officers_after_full_enquiries_have_never_been_the;
	}
	public void setThe_company_its_subsidiaries_and_its_directors_or_officers_after_full_enquiries_have_never_been_the(
			String the_company_its_subsidiaries_and_its_directors_or_officers_after_full_enquiries_have_never_been_the) {
		this.the_company_its_subsidiaries_and_its_directors_or_officers_after_full_enquiries_have_never_been_the = the_company_its_subsidiaries_and_its_directors_or_officers_after_full_enquiries_have_never_been_the;
	}
	public String getInitial_starting_date() {
		return initial_starting_date;
	}
	public void setInitial_starting_date(String initial_starting_date) {
		this.initial_starting_date = initial_starting_date;
	}
	public String getExpiring_date() {
		return expiring_date;
	}
	public void setExpiring_date(String expiring_date) {
		this.expiring_date = expiring_date;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	private String email;

}
